import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";
const html = fs.readFileSync(new URL("../docs/index.html", import.meta.url), "utf8");
const start = html.indexOf("function saveAdd(");
const end = html.indexOf("/* ── Edit flow", start);
const error = { textContent: "" };
const context = vm.createContext({ store: { session: null }, demoMode: false, $: () => error });
vm.runInContext(html.slice(start, end), context);
vm.runInContext("saveAdd()", context);
assert.match(error.textContent, /Sign in/);
context.store.session = { user_id: "fixture" };
context.demoMode = true;
error.textContent = "";
vm.runInContext("saveAdd()", context);
assert.match(error.textContent, /Sign in/);
assert.match(html, /first 20 saves/);
assert.doesNotMatch(html, /first 50 saves/);
console.log("Account rules: signed-out and demo writes rejected; 20-save copy aligned.");
