import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";
import {PGlite} from "@electric-sql/pglite";
const c=vm.createContext({});
vm.runInContext(fs.readFileSync("docs/saved-content.js","utf8")+fs.readFileSync("docs/enrichment.js","utf8")+";globalThis.rules=Enrichment;globalThis.Queue=EnrichmentQueue",c);
assert.equal(c.rules.due({image_url:"existing"}),true);
assert.equal(c.rules.due({enrichment_attempts:3}),false);
const row={id:"one",title:"My title",title_edited:true,category_id:"health",tags:["mine"],updated_at:"one",note_text:"private"};
const preview=c.rules.preview(row,{title:"Automatic title",description:"Captured text"},"a");
assert.equal(preview.title,"My title"); assert.equal(preview.body_text,"Captured text");
assert.ok(!Object.hasOwn(preview,"category_id")); assert.ok(!Object.hasOwn(preview,"note_text"));
let saves=0, changed=0, rows=[row], release;
const queue=new c.Queue({session:()=>({user_id:"owner"}),rows:()=>rows,preview:()=>new Promise(r=>release=r),save:async()=>{saves++;return [row]},changed:()=>changed++,clock:()=>9000000});
const pending=queue.run(); row.updated_at="edited"; release({}); await pending; assert.equal(saves,0);
const queue2=new c.Queue({session:()=>({user_id:"owner"}),rows:()=>Array.from({length:30},(_,i)=>({id:String(i),updated_at:"one"})),preview:async()=>({}),save:async r=>{saves++;return [r]},changed:()=>changed++,clock:()=>9000000});
await queue2.run(); assert.equal(saves,4); await queue2.run(); assert.equal(saves,8);
const db=new PGlite();
await db.exec(`create role authenticated; create schema auth; create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table bookmarks(id text,owner_id uuid,title text,body_text text,image_url text,author text,updated_at timestamptz,deleted_at timestamptz,category_id text,tags text[],note_text text);
alter table bookmarks enable row level security; create policy own on bookmarks for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
grant usage on schema public,auth to authenticated; grant select,update on bookmarks to authenticated;`);
await db.exec(fs.readFileSync("supabase/migrations/0016_enrichment_provenance.sql","utf8"));
await db.exec(`insert into bookmarks(id,owner_id,title,updated_at,title_edited,category_id,tags,note_text) values('one','11111111-1111-4111-8111-111111111111','Mine','2026-09-12',true,'health',array['mine'],'private');set role authenticated;select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);`);
const payload=JSON.stringify({title:"Automatic",body_text:"Captured text",enrichment_version:2});
assert.equal((await db.query("select * from apply_bookmark_preview('one','2026-09-11',$1)",[payload])).rows.length,0);
const saved=(await db.query("select * from apply_bookmark_preview('one','2026-09-12',$1)",[payload])).rows[0];
assert.equal(saved.title,"Mine"); assert.equal(saved.body_text,"Captured text"); assert.equal(saved.category_id,"health"); assert.equal(saved.note_text,"private"); assert.deepEqual(saved.tags,["mine"]);
await db.exec("select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false)");
assert.equal((await db.query("select * from apply_bookmark_preview('one',$1,$2)",[saved.updated_at,payload])).rows.length,0);
await db.close();
console.log("Enrichment bounds/resume, in-flight edit race, PostgreSQL CAS and owner isolation passed.");
